#pragma once

#define JARVIS_PROTOCOL_VERSION 1
#define JARVIS_MAX_CONTROL_BYTES 8192
#define JARVIS_MAX_AUDIO_CHUNK_BYTES 16384

typedef enum {
    JARVIS_MESSAGE_INVALID,
    JARVIS_MESSAGE_PING,
    JARVIS_MESSAGE_PLAY_AUDIO_START,
    JARVIS_MESSAGE_PLAY_AUDIO_END,
    JARVIS_MESSAGE_START_LISTENING,
    JARVIS_MESSAGE_STOP_LISTENING,
    JARVIS_MESSAGE_RETURN_IDLE,
    JARVIS_MESSAGE_SET_DISPLAY_STATE,
} jarvis_message_type_t;

jarvis_message_type_t jarvis_message_type(const char *name);
